services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend.Dockerfile
    working_dir: /app
    command: sh -c "pnpm install && pnpm dev --hostname 0.0.0.0 --port 3000"
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    networks:
      - hephaestus-net

  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend.Dockerfile
    working_dir: /app
    command: sh -c "air -c .air.toml"
    environment:
      PORT: "8080"
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    networks:
      - hephaestus-net

networks:
  hephaestus-net:
    driver: bridge

volumes:
  frontend_node_modules:
